### ISSUE TITLE
Airtable API key

### ISSUE THREAD

**Issue by aimatus** [juanmnl/covid19-monitor#30]
Hello!

I'm trying to run the app locally, but I'm having issues. I've created an Airtable API key because it seems to be necessary to load provinces and I added it to `./env.local` as `REACT_APP_AIRTABLE_API_KEY=keyMySecretKey12345`, but it doesn't seem to work. Is there something else I need to do? Am I doing things wrong?

Thanks for your help!

**Comment by juanmnl** [comment]
hey @aimatus there's a new addition explaining airtable in `docs/run-instructions.md`

Hope it works, but let me know if it doesn't :)

**Comment by juanmnl** [comment]
It's right on the readme, sorry about that

**Comment by aimatus** [comment]
Tank you very much! Now I got rid of that issue!
